-- CB ScriptStore: statistics + profile avatar + public Raw support
-- Jalankan di Supabase SQL Editor.

create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  visitor_id text,
  path text,
  created_at timestamptz not null default now()
);
create index if not exists site_visits_created_at_idx on public.site_visits(created_at);

create table if not exists public.presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  last_seen timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  avatar_url text default 'profil1.png',
  created_at timestamptz not null default now()
);
alter table public.profiles add column if not exists avatar_url text default 'profil1.png';

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, username) values (new.id, new.raw_user_meta_data->>'username')
  on conflict (id) do update set username=coalesce(excluded.username, public.profiles.username);
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- Backfill profiles for accounts that already existed.
insert into public.profiles(id, username)
select id, raw_user_meta_data->>'username' from auth.users
on conflict (id) do nothing;

alter table public.site_visits enable row level security;
alter table public.presence enable row level security;
alter table public.profiles enable row level security;

-- Public site statistics.
drop policy if exists "public can record visits" on public.site_visits;
create policy "public can record visits" on public.site_visits for insert to anon, authenticated with check (true);
drop policy if exists "public can read visit stats" on public.site_visits;
create policy "public can read visit stats" on public.site_visits for select to anon, authenticated using (true);

drop policy if exists "authenticated presence write" on public.presence;
create policy "authenticated presence write" on public.presence for all to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "public can read presence" on public.presence;
create policy "public can read presence" on public.presence for select to anon, authenticated using (true);

drop policy if exists "public can read profiles" on public.profiles;
create policy "public can read profiles" on public.profiles for select to anon, authenticated using (true);
drop policy if exists "user can update own profile" on public.profiles;
create policy "user can update own profile" on public.profiles for update to authenticated using (auth.uid()=id) with check (auth.uid()=id);

-- IMPORTANT: keep your existing scripts policies. Raw page only reads scripts where visibility='public'.
-- If your scripts table already exists, no change is needed here.
