-- CB ScriptStore — Supabase setup for GitHub Pages (no Render/backend server)
-- Run this whole file in Supabase Dashboard -> SQL Editor.
-- Then disable Authentication -> Providers -> Email -> Confirm email, because CB ScriptStore uses username + password without real email addresses.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null check (username ~ '^[A-Za-z0-9_]{5,24}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists profiles_username_lower_unique on public.profiles (lower(username));

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (new.id, new.raw_user_meta_data ->> 'username');
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create table if not exists public.scripts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  filename text not null check (char_length(filename) between 1 and 120),
  code text not null default '' check (char_length(code) <= 500000),
  visibility text not null default 'private' check (visibility in ('private','public')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists scripts_user_updated_idx on public.scripts(user_id, updated_at desc, id desc);

create or replace function public.enforce_script_limit()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  if (select count(*) from public.scripts where user_id = new.user_id) >= 50 then
    raise exception 'Maximum 50 scripts per account.' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

drop trigger if exists scripts_limit_50 on public.scripts;
create trigger scripts_limit_50 before insert on public.scripts
for each row execute procedure public.enforce_script_limit();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists scripts_set_updated_at on public.scripts;
create trigger scripts_set_updated_at before update on public.scripts
for each row execute procedure public.set_updated_at();

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  message text not null check (char_length(message) between 1 and 500),
  created_at timestamptz not null default now()
);
create index if not exists chat_messages_created_idx on public.chat_messages(id desc);

create table if not exists public.presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  last_seen timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.scripts enable row level security;
alter table public.chat_messages enable row level security;
alter table public.presence enable row level security;

drop policy if exists profiles_select_authenticated on public.profiles;
create policy profiles_select_authenticated on public.profiles
for select to authenticated using (true);

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists scripts_select_own_or_public on public.scripts;
create policy scripts_select_own_or_public on public.scripts
for select to authenticated using (auth.uid() = user_id or visibility = 'public');

drop policy if exists scripts_insert_own on public.scripts;
create policy scripts_insert_own on public.scripts
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists scripts_update_own on public.scripts;
create policy scripts_update_own on public.scripts
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists scripts_delete_own on public.scripts;
create policy scripts_delete_own on public.scripts
for delete to authenticated using (auth.uid() = user_id);

drop policy if exists chat_select_authenticated on public.chat_messages;
create policy chat_select_authenticated on public.chat_messages
for select to authenticated using (true);

drop policy if exists chat_insert_own on public.chat_messages;
create policy chat_insert_own on public.chat_messages
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists presence_select_authenticated on public.presence;
create policy presence_select_authenticated on public.presence
for select to authenticated using (true);

drop policy if exists presence_insert_own on public.presence;
create policy presence_insert_own on public.presence
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists presence_update_own on public.presence;
create policy presence_update_own on public.presence
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists presence_delete_own on public.presence;
create policy presence_delete_own on public.presence
for delete to authenticated using (auth.uid() = user_id);

-- Public raw links are read through the anon role.
drop policy if exists scripts_public_read_anon on public.scripts;
create policy scripts_public_read_anon on public.scripts
for select to anon using (visibility = 'public');

-- Realtime is not required: this project uses lightweight polling for online/chat updates.


-- FIX: PostgREST relationship support for profiles(username).
-- The frontend embeds profiles from chat_messages and presence, so these
-- tables must have foreign keys to public.profiles (not only auth.users).
-- Run this section after the original setup if the tables already exist.

-- Make sure every existing auth user has a profile row.
insert into public.profiles (id, username)
select
  u.id,
  coalesce(
    nullif(u.raw_user_meta_data ->> 'username', ''),
    'user_' || substr(replace(u.id::text, '-', ''), 1, 18)
  )
from auth.users u
where not exists (select 1 from public.profiles p where p.id = u.id)
  and coalesce(nullif(u.raw_user_meta_data ->> 'username', ''), 'user_' || substr(replace(u.id::text, '-', ''), 1, 18)) ~ '^[A-Za-z0-9_]{5,24}$'
 on conflict (id) do nothing;

-- Replace user_id foreign keys with public.profiles relationships so
-- Supabase can resolve profiles(username) in nested selects.
do $$
declare
  r record;
begin
  for r in
    select c.conrelid::regclass as table_name, c.conname
    from pg_constraint c
    join pg_attribute a on a.attrelid = c.conrelid and a.attnum = any(c.conkey)
    where c.contype = 'f'
      and c.confrelid = 'auth.users'::regclass
      and a.attname = 'user_id'
      and c.conrelid in ('public.scripts'::regclass, 'public.chat_messages'::regclass, 'public.presence'::regclass)
  loop
    execute format('alter table %s drop constraint if exists %I', r.table_name, r.conname);
  end loop;
end $$;

alter table public.scripts
  drop constraint if exists scripts_user_id_profiles_fkey,
  add constraint scripts_user_id_profiles_fkey foreign key (user_id) references public.profiles(id) on delete cascade;

alter table public.chat_messages
  drop constraint if exists chat_messages_user_id_profiles_fkey,
  add constraint chat_messages_user_id_profiles_fkey foreign key (user_id) references public.profiles(id) on delete cascade;

alter table public.presence
  drop constraint if exists presence_user_id_profiles_fkey,
  add constraint presence_user_id_profiles_fkey foreign key (user_id) references public.profiles(id) on delete cascade;

